# RAML 0.0

title: Notify service API
version: v1
mediaType: application/json

/api/{version}:
  uriParameters:
    version:
      description: "API version"
      type: string

  /notify/{backends}:
    uriParameters:
      backends:
        description: "Comma-separated backends names"
        type: string

    post:
      description: "Send notifications to given backends"
      responses:
        200:
          body:
            schema: !include schemas/post/notify_backends.json
            example: !include response_examples/200/notify_backends.json
